version: "3.8"
services:
  backend:
    build:
      context: ./be-shipping
      dockerfile: Dockerfile
    container_name: be-shipping-3
    ports:
      - "4000:4000" # Port สำหรับ Backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: ct648
    depends_on:
      - db
  frontend:
    build:
      context: ./fe-shopping
      dockerfile: Dockerfile
    container_name: fe-shopping-3
    ports:
      - "3000:3000" # Port สำหรับ Frontend
    depends_on:
      - backend
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ct648
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  db_data:
